title: María Copello
description: Salesforce Marketing Cloud Developer
url: "https://mabecoart.com"
baseurl: ""

# Build settings
markdown: kramdown
permalink: /:path.html

plugins:
  - jekyll-sitemap

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
