title: María Copello
description: Digital Marketing Developer
url: "https://mabecoart.com"
baseurl: ""

# Build settings
markdown: kramdown
permalink: pretty

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
